import numpy as np
import time

a = np.array([[2],[2],[2]])
a = np.random.rand(60000)
print("Shape of a ", np.shape(a))
b = np.array([[0.5, 0.25], [0.5, 0.25]])
b = np.random.rand(10,9)
print("Shape of b ", np.shape(b))
print(np.multiply.types)
t1 = time.time()
X = np.array([x * y for x in a for y in b])
# print(X)
t2 = time.time()
print("Time taken for range expression ", t2 - t1)
t3 = time.time()
Y = np.multiply.outer(a,b)
t4 = time.time()
print("Time taken for u func ", t4 - t3)
print("Shape of Y ", np.shape(Y))
# print(Y)
sW = np.sum(Y, axis=0)
print("Shape of sW ", np.shape(sW))
print("Reduction in time with vectorization " , 100 - ((t4-t3)/(t2-t1)*100))
# print(sW)
# x = np.random.randn(4,2,2)
# print(x)
# y = np.reshape(x, (8,2))
# print(y)
# # c = a / (b * (1 - b))
# # print(c)

# print("a= ", a)
# d = np.sum(a, axis=1, keepdims=False)
# e = np.sum(a, axis=1, keepdims=True)
# print(d)
# print(e)

